version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      _JAVA_OPTIONS: "-Xms1024m -Xmx2048m"
      TERM: dumb
    working_directory: ~/ms-dashboard-server
    steps:
      - checkout
      - restore_cache:
          key: ms-dashboard-server-{{ .Branch }}
      - run:
          name: "Download dependencies"
          command: ./mvnw -s .settings.xml -U --fail-never dependency:go-offline || true
      - save_cache:
          key: ms-dashboard-server-{{ .Branch }}
          paths:
            - ~/.m2
      - run:
          name: "Running build"
          command: ./mvnw -s .settings.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent install -U -P sonar -nsu --batch-mode -Dmaven.test.redirectTestOutputToFile=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - run:
          name: "Aggregate built jars"
          when: always
          command: |
            mkdir -p jars/
            find . -type f -name "*.jar" -and \( \
              -path "*/microservices-dashboard-server-core/target/*" \
              \) \
              -exec cp {} jars/ \;
      - run:
          name: "Aggregate test results"
          when: always
          command: |
            mkdir -p junit/
            find . -type f -regex ".*/target/.*-reports/.*" -exec cp {} junit/ \;
            bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: jars/
          destination: artifacts
      - store_test_results:
          path: junit/
          destination: testartifacts
  update-documentation:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      TERM: dumb
    working_directory: ~/ms-dashboard-server
    steps:
      - add_ssh_keys:
          fingerprints:
            - "d3:f4:e3:72:8d:47:79:f5:d9:7b:59:bc:06:80:e1:47"
      - checkout
      - restore_cache:
          key: ms-dashboard-server-documentation
      - run:
          name: Updating GitHub Pages
          command: |
            git config --global user.email "buildmaster@ordina.be"
            git config --global user.name "ordina-buildmaster"
            ./docs/src/main/scripts/ghpages.sh -b
      - save_cache:
          key: ms-dashboard-server-documentation
          paths:
            - ~/.m2

notify:
  webhooks:
    # A list of hook hashes, containing the url field
    # gitter hook
    - url: https://webhooks.gitter.im/e/ab22eaaa0faf911ac32f

workflows:
  version: 2
  build-and-update-documentation:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages # list of branches to ignore
                - 1.x
      - update-documentation:
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
          requires:
            - build